// Package http_server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package http_server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	Code      string `json:"code"`
	RequestId string `json:"requestId"`
}

// ListMeta defines model for ListMeta.
type ListMeta struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
	Total  int `json:"total"`
}

// TokenCreate defines model for TokenCreate.
type TokenCreate struct {
	LoginId  string `json:"loginId"`
	Password string `json:"password"`
}

// TokenInfo defines model for TokenInfo.
type TokenInfo struct {
	ExpiresAt time.Time `json:"expiresAt"`
	IssuedAt  time.Time `json:"issuedAt"`
	Token     string    `json:"token"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    string `json:"email"`
	LoginId  string `json:"loginId"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email   string `json:"email"`
	Id      string `json:"id"`
	LoginId string `json:"loginId"`
	Phone   string `json:"phone"`
}

// UserInfoList defines model for UserInfoList.
type UserInfoList struct {
	Metadata ListMeta   `json:"metadata"`
	Users    []UserInfo `json:"users"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Email    string `json:"email"`
	Id       string `json:"id"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
}

// Limit defines model for Limit.
type Limit int

// Offset defines model for Offset.
type Offset int

// UserID defines model for UserID.
type UserID string

// PostTokensJSONBody defines parameters for PostTokens.
type PostTokensJSONBody TokenCreate

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Offset *Offset `json:"Offset,omitempty"`
	Limit  *Limit  `json:"Limit,omitempty"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody UserCreate

// PutUsersUserIDJSONBody defines parameters for PutUsersUserID.
type PutUsersUserIDJSONBody UserUpdate

// PostTokensJSONRequestBody defines body for PostTokens for application/json ContentType.
type PostTokensJSONRequestBody PostTokensJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody

// PutUsersUserIDJSONRequestBody defines body for PutUsersUserID for application/json ContentType.
type PutUsersUserIDJSONRequestBody PutUsersUserIDJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /tokens)
	PostTokens(w http.ResponseWriter, r *http.Request)

	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams)

	// (POST /users)
	PostUsers(w http.ResponseWriter, r *http.Request)

	// (DELETE /users/{UserID})
	DeleteUsersUserID(w http.ResponseWriter, r *http.Request, userID UserID)

	// (GET /users/{UserID})
	GetUsersUserID(w http.ResponseWriter, r *http.Request, userID UserID)

	// (PUT /users/{UserID})
	PutUsersUserID(w http.ResponseWriter, r *http.Request, userID UserID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// PostTokens operation middleware
func (siw *ServerInterfaceWrapper) PostTokens(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTokens(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "Offset" -------------
	if paramValue := r.URL.Query().Get("Offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "Offset", r.URL.Query(), &params.Offset)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter Offset: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "Limit" -------------
	if paramValue := r.URL.Query().Get("Limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "Limit", r.URL.Query(), &params.Limit)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter Limit: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "UserID" -------------
	var userID UserID

	err = runtime.BindStyledParameter("simple", false, "UserID", chi.URLParam(r, "UserID"), &userID)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter UserID: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUsersUserID(w, r, userID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "UserID" -------------
	var userID UserID

	err = runtime.BindStyledParameter("simple", false, "UserID", chi.URLParam(r, "UserID"), &userID)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter UserID: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersUserID(w, r, userID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PutUsersUserID operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "UserID" -------------
	var userID UserID

	err = runtime.BindStyledParameter("simple", false, "UserID", chi.URLParam(r, "UserID"), &userID)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter UserID: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUsersUserID(w, r, userID)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tokens", wrapper.PostTokens)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{UserID}", wrapper.DeleteUsersUserID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{UserID}", wrapper.GetUsersUserID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{UserID}", wrapper.PutUsersUserID)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xX32/bNhD+V4LbHllJc5MB09O6NhgCZD+ANU+FHzjpbLMRRZY8JTMC/e8Df1hSKsmx",
	"i7oYkr3ZIu/uu7uP35EPUCipVY01WcgfQHPDJRIa/+9aSEHuh6ghh08Nmi0wqLlEyOMiA1tsUHK3q8QV",
	"byqC/CJjQFvtdomacI0G2pbBH6uVxVl/cXXoUIpayEZCPu3vxqK5etf505w2vbu4yMDgp0YYLCEn0+DQ",
	"fXRpyYh6Da1zGRZ98pfGKHNVr5Svi1EaDQn0S4UqccJBiIWWrsop90MoH4KPocWyy1H9/RELcv6uhaXf",
	"kPgYQrVrzed1YaC6Mo/XSBGvppY+Q1fF5qpdU4LhFMb36hbrtwY54QRMtRb1ZDkYaG7tvTIH1GrnZWAz",
	"i2S6Y/iPFgbtG1+WlTKSE+RQcsJXJKRrxAiesLbB8hgLcvGfziZsGwRgA3hTeTkqzxUYJRfVZHm/sPQM",
	"9EbV+EVN2dmyCGsumZkezaYiyuMzPCwJ4UAPMjkYvjuZ4xQkEi95OK/fG1xBDt+lvcKmUV7S7ly3DBob",
	"1VYQSvuUZVe+tgPHjeHbUWbBLeshzWVzo8sjmSVORypxJJ+cvYhsKlRNvKABdrCNto2++PF88fPafUoK",
	"JR2aEm1hhCah3OCwttGLW6Qz3tDmzKK5E4ULWokCa+tRx6HyRvNig2eLJAMGjXEhNkQ6T9P7+/uE+9VE",
	"mXUaTW16ffX28ve/Ll8tkizZkKx83wRVuCfuHRobkP2QZEnmNV1jzbWAHF77T8xPO9+n1OtJmN4qkNK1",
	"kbvk3OGAP5Wl92FPN29+UeV2VzOsvRHXuhKFN0s/WuWFrJ+V+zg5nABtG1pqtXL5O9NFln3dUIH/7aiP",
	"rlDnXzFYfwOYCXbx7YI52vC17efH0n1KO/FY40Tnf0W6iTIwvNh9mEbSb0njXaxlT+4Mt8B2ecKeP5Lc",
	"/0Lbz7Pz584xxytYOt2elZQds06hKIMbz4kFpZ+nL1ZPYq87OUkfwtupDW+6CsPt4DED3vnvngODl9a4",
	"SS/79OxV5b11e37kflGqedS0jURwQ1Q3U2rbjAhzGsmNT4F5yf2fQt9KjFsG7kGwY9BhD5ZHLxKuRVLe",
	"Knv3OvnJNDIpCmiX7b8BAAD//zjDtYjxEwAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
