// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ssup2ket/ssup2ket-auth-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/ssup2ket/ssup2ket-auth-service/internal/domain/repo"

	uuid "github.com/ssup2ket/ssup2ket-auth-service/pkg/model/uuid"
)

// UserOutboxRepo is an autogenerated mock type for the UserOutboxRepo type
type UserOutboxRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userInfo
func (_m *UserOutboxRepo) Create(ctx context.Context, userInfo *model.UserOutbox) error {
	ret := _m.Called(ctx, userInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserOutbox) error); ok {
		r0 = rf(ctx, userInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, userUUID
func (_m *UserOutboxRepo) Delete(ctx context.Context, userUUID uuid.ModelUUID) error {
	ret := _m.Called(ctx, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.ModelUUID) error); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *UserOutboxRepo) WithTx(tx *repo.DBTx) repo.UserOutboxRepo {
	ret := _m.Called(tx)

	var r0 repo.UserOutboxRepo
	if rf, ok := ret.Get(0).(func(*repo.DBTx) repo.UserOutboxRepo); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.UserOutboxRepo)
		}
	}

	return r0
}
