// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	authtoken "github.com/ssup2ket/ssup2ket-auth-service/pkg/authtoken"

	mock "github.com/stretchr/testify/mock"
)

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: ctx, loginID, passwd
func (_m *TokenService) CreateToken(ctx context.Context, loginID string, passwd string) (*authtoken.AuthTokenInfo, error) {
	ret := _m.Called(ctx, loginID, passwd)

	var r0 *authtoken.AuthTokenInfo
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *authtoken.AuthTokenInfo); ok {
		r0 = rf(ctx, loginID, passwd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authtoken.AuthTokenInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, loginID, passwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
