// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ssup2ket/service-auth/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/ssup2ket/service-auth/pkg/entity/uuid"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, userInfo, passwd
func (_m *UserService) CreateUser(ctx context.Context, userInfo *entity.UserInfo, passwd string) (*entity.UserInfo, error) {
	ret := _m.Called(ctx, userInfo, passwd)

	var r0 *entity.UserInfo
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserInfo, string) *entity.UserInfo); ok {
		r0 = rf(ctx, userInfo, passwd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.UserInfo, string) error); ok {
		r1 = rf(ctx, userInfo, passwd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, userUUID
func (_m *UserService) DeleteUser(ctx context.Context, userUUID uuid.EntityUUID) error {
	ret := _m.Called(ctx, userUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.EntityUUID) error); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, userUUID
func (_m *UserService) GetUser(ctx context.Context, userUUID uuid.EntityUUID) (*entity.UserInfo, error) {
	ret := _m.Called(ctx, userUUID)

	var r0 *entity.UserInfo
	if rf, ok := ret.Get(0).(func(context.Context, uuid.EntityUUID) *entity.UserInfo); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.EntityUUID) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUser provides a mock function with given fields: ctx, offset, limit
func (_m *UserService) ListUser(ctx context.Context, offset int, limit int) ([]entity.UserInfo, error) {
	ret := _m.Called(ctx, offset, limit)

	var r0 []entity.UserInfo
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.UserInfo); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, userInfo, passwd
func (_m *UserService) UpdateUser(ctx context.Context, userInfo *entity.UserInfo, passwd string) error {
	ret := _m.Called(ctx, userInfo, passwd)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserInfo, string) error); ok {
		r0 = rf(ctx, userInfo, passwd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserService(t mockConstructorTestingTNewUserService) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
