name: test-integration

on:
  workflow_run:
    workflows: [test-unit]
    branches: [master]
    types: [completed]

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'local_auth'
        mysql root password: 'root'

    - name: Install grpcurl
      run: go install github.com/fullstorydev/grpcurl/cmd/grpcurl@v1.8.2

    - name: Run auth service and integration test
      run: |
        CGO_ENABLED=0 GO111MODULE=on go build -a -o ssup2ket-auth ./cmd/ssup2ket-auth
        . scripts/env-local && sudo -E ./ssup2ket-auth &
        sleep 30s
        scripts/test-http-server.sh
        scripts/test-grpc-server.sh
